spring:
  profiles:
    active: dev
---
server:
  port: 8081
spring:
  profiles: dev
  application:
    name: cloud-eureka-center01
eureka:
  instance:
    hostname: cloud-eureka-center01.com
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://cloud-eureka-center01.com:8081/eureka