spring:
  profiles:
    active: dev
---
server:
  port: 8082
spring:
  profiles: dev
  application:
    name: cloud-eureka-center02
eureka:
  instance:
    hostname: cloud-eureka-center01.com
  client:
    # fetch-registry: false
    # register-with-eureka: false
    service-url:
      defaultZone: http://cloud-eureka-center01.com:8081/eureka