spring:
  profiles:
    active: dev
---
server:
  port: 8082
  context-path: /eureka
spring:
  profiles: dev
  application:
    name: cloud-eureka-center
eureka:
  instance:
    hostname: cloud-eureka-center02.com
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://cloud-eureka-center01.com:8081/eureka