spring:
  profiles:
    active: dev
---
server:
  port: 8081
  context-path: /eureka
spring:
  profiles: dev
  application:
    name: cloud-eureka-center01
eureka:
  instance:
    hostname: cloud-eureka-center01.com
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://cloud-eureka-center02.com:8082/eureka